---
- hosts: localhost
  vars_files:
    - vault.yml
  become: yes
  connection: local
  roles:
    - sudo

- hosts: onitato
  vars_files:
    - vault.yml
  become: yes
  roles:
    - fail2ban
    - firewall
    - sshd
    - sudo
