- hosts: onitato
  become: yes
  tasks:
  - name: Run package updates
    apt: upgrade=dist

- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Run package updates
    apt: upgrade=dist
